from pydantic import Field

from pardner.verticals import BaseVertical


class ChatBotVertical(BaseVertical):
    """An instance of a chatbot created by ``creator_user_id``."""

    vertical_name: str = 'chat_bot'

    name: str | None = None
    conversation_group_id: str | None = Field(
        description='Generated by the service.', default=None
    )
